# Generated by Django 4.2.27 on 2026-01-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita_Medicamento',
            new_name='ReceitaMedicamento',
        ),
        migrations.AlterField(
            model_name='receita',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='clinica.consulta'),
        ),
    ]
