# Generated by Django 4.2.27 on 2026-01-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('colaterais', models.TextField(max_length=500)),
                ('tipo_de_uso', models.CharField(max_length=20)),
                ('tarja', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('RG', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=320)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(max_length=5)),
                ('alergias', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_usar', models.TextField(max_length=500)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Receita_Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=50)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.receita')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('RG', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=320)),
                ('endereco', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=40)),
                ('ativo_atualmente', models.BooleanField(default=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='clinica.especialidade')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='clinica.medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='clinica.paciente'),
        ),
    ]
