# Generated by Django 4.2.27 on 2026-01-29 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('duracao_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.cultura')),
            ],
        ),
        migrations.CreateModel(
            name='propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='usoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Uso_de_insumos', to='agronegocio.insumo')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Uso_de_Insumos', to='agronegocio.plantio')),
            ],
        ),
        migrations.AddField(
            model_name='plantio',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantios', to='agronegocio.propriedade'),
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=25)),
                ('RG', models.CharField(max_length=20)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Funcionarios', to='agronegocio.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colheitas', to='agronegocio.plantio')),
            ],
        ),
    ]
